version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres_db_logistica
    environment:
      POSTGRES_DB: logistica
      POSTGRES_USER: logistica_user
      POSTGRES_PASSWORD: logistica_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=logistica
      - DB_USER=logistica_user
      - DB_PASS=logistica_pass

volumes:
  db_data: